version: '3.3'

services:
  nuxt:
    build:
      context: .
    image: nixel666/infomania_ssr
    container_name: nuxt_dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"