export enum Routes {
  META_ROUTE = '/api/meta',
  META_MODEL_ROUTE = '/api/meta/model',
  LOGIN_ROUTE = '/api/auth/login',
  BULK_CREATE_ROUTE = '/api/bulk/create',
  ENTRY_ROUTE = '/api/entry/',
  MENU_ROUTE = '/api/menu/',
  MENU_MENU_ITEMS_ROUTE = '/api/menu/menu-items/',
  MENU_ITEM_ROUTE = '/api/menu-item/',
  DEPARTMENT_ROUTE = '/api/department/',
  RUBRIC_ROUTE = '/api/rubric/',
  AFFICHE_ROUTE = '/api/affiche/',
  UPLOAD_ROUTE = '/api/upload/',
  UPLOAD_EXHIBITION_ROUTE = '/api/upload/exhibition/',
  MAIN_SLIDER_ROUTE = '/api/main-slider/',
  FILE_ROUTE = '/api/file/',
  DOCUMENT_ROUTE = '/api/document/',
  GAMES_ROUTE = '/api/games/',
  GAMES_RANDOM_ROUTE = '/api/games/random',
  GENRE_ROUTE = '/api/genre/',
  NOTIFICATION_ROUTE = '/api/notification/',
  BOOK_ROUTE = '/api/book/',
  COLLECTION_ROUTE = '/api/collection/',
}
